language: generic

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6

before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90

go_import_path: gopkg.in/src-d/lookout-sdk.v0

stages:
  - name: test
  - name: release
    if: tag IS present

jobs:
  include:
    - name: "Python: example integration tests"
      stage: test
      language: python
      python: "3.6"
      install:
        - pip3 install -e python
      script:
        - ./_tools/install-lookout-latest.sh
        - (python3 language-analyzer.py |& tee -a ./py-analyzer.log)&
        - ./lookout-sdk review --log-level=debug --from 0a9d1d159d2b0064c32df8d2287b174a91390b1a --to HEAD "ipv4://localhost:2021"
      after_failure:
        - echo "test"
        - cat ./py-analyzer.log
        - cat ./lookout-install.log

    - name: "Golang: example integration tests"
      stage: test
      language: go
      go: "1.10"
      install:
        - go version
        - go get .
      script:
        - ./_tools/install-lookout-latest.sh
        - (go run language-analyzer.go |& tee -a ./go-analyzer.log)&
        - sleep 1s
        - ./lookout-sdk review --log-level=debug --from 0a9d1d159d2b0064c32df8d2287b174a91390b1a --to HEAD "ipv4://localhost:2020"
      after_failure:
        - cat ./go-analyzer.log
        - cat ./lookout-install.log

    - name: "Generated code"
      stage: test
      language: go
      go: "1.10"
      env:
        - PYENV_VERSION="3.6"
      script:
        - make protogen
        - make no-changes-in-commit

    - name: "Python: release a library"
      stage: release
      language: python
      python: "3.6"
      before_script:
        - pip3 install twine
        - cd python
      script:
        - python3 setup.py bdist_wheel
        - twine upload dist/*py3-none-any* -u $PYPI_LOGIN -p $PYPI_PASS
      skip_cleanup: true


cache:
  directories:
    - $HOME/protoc
    - $HOME/.cache/pip/wheels
